---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04
      box_url: /Users/veerbahadurshukla/Software/ubuntu-14.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[chefCI::default]
    attributes:
